services:
  - type: web
    name: smarttrace-backend
    runtime: docker
    env: docker
    rootDir: SmartTrace-backend
    plan: free
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_SSL
        value: "true"
      - key: PORT
        value: "3000"
  - type: web
    name: smarttrace-frontend
    runtime: docker
    env: docker
    rootDir: SmartTrace-frontend
    plan: free
    envVars:
      - key: BACKEND_URL
        value: "http://smarttrace-backend:3000"
